name: inno_bundle
description: CLI tool for automating Windows installer creation using Inno Setup.
maintainer: Hocine Abdellatif Houari
version: 0.7.5
homepage: https://github.com/hahouari/inno_bundle

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  windows:

dependencies:
  flutter:
    sdk: flutter
  args: ^2.5.0
  yaml: ^3.1.2
  uuid: ^4.5.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
