name: inno_bundle
description: CLI tool for automating Windows installer creation using Inno Setup.
maintainer: Hocine Abdellatif Houari
version: 0.3.2
homepage: https://github.com/hahouari/inno_bundle

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.2
  yaml: ^3.1.2
  uuid: ^4.2.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
